version: '2'
services: 
  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
    volumes:
      - ./concourse-data:/database

  concourse-web:
    image: concourse/concourse:3.14.1
    links: [concourse-db]
    command: web
    ports: ["9095:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme 
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_BAGGAGECLAIM_DRIVER: naive
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable


  concourse-worker-1:
    image: concourse/concourse:3.14.1
    privileged: true
    links: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
      CONCOURSE_BAGGAGECLAIM_DRIVER: naive

  
  minio:
    image: minio/minio
    environment:
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
    volumes: ["./data:/data", "./minio-config:/root/.minio"]
    command: server /data

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry